# Generated by Django 3.0.5 on 2020-04-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profiles/', verbose_name="Player's image")),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('CM', 'Center Midfield'), ('AM', 'Attacking Midfield'), ('CF', 'Center Forward'), ('ST', 'Striker')], default='Choose position', max_length=50, verbose_name='Player position')),
                ('bio', models.TextField(blank=True, verbose_name="Player's Biography")),
            ],
        ),
        migrations.CreateModel(
            name='Pom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
