# Generated by Django 3.0.5 on 2020-04-23 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200423_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pom',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='pom', to='player.Player'),
        ),
    ]
