# Generated by Django 3.0.5 on 2020-04-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20200423_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='pom',
            name='pom',
            field=models.BooleanField(default=False, verbose_name='P.O.M'),
        ),
    ]
