# Generated by Django 3.0.5 on 2020-04-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20200424_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.BooleanField(default=False, verbose_name='Captain')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='captain', to='player.Player')),
            ],
        ),
    ]
