# Generated by Django 3.0.5 on 2020-04-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/', verbose_name="Player's image"),
        ),
    ]
