# Generated by Django 3.0.5 on 2020-04-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20200424_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pom',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='captain',
            field=models.BooleanField(default=False, unique=True, verbose_name='Captain'),
        ),
        migrations.AddField(
            model_name='player',
            name='pom',
            field=models.BooleanField(default=False, unique=True, verbose_name='Player of the month'),
        ),
        migrations.DeleteModel(
            name='Captain',
        ),
        migrations.DeleteModel(
            name='Pom',
        ),
    ]
