# Generated by Django 3.0.5 on 2020-04-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_auto_20200424_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='captain',
            field=models.BooleanField(default=False, verbose_name='Captain'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pom',
            field=models.BooleanField(default=False, verbose_name='Player of the month'),
        ),
    ]
